<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="2" passed="0">
  <reporter-output>
    <line>
      <![CDATA[About to begin executing test Random Sanity Test Demo]]>
    </line>
    <line>
      <![CDATA[About to begin executing Framework_001.beforeMethod]]>
    </line>
    <line>
      <![CDATA[Completed executing Framework_001.beforeMethod]]>
    </line>
    <line>
      <![CDATA[About to begin executing Framework_001.VerificationDuringCall]]>
    </line>
    <line>
      <![CDATA[Completed executing Framework_001.VerificationDuringCall]]>
    </line>
    <line>
      <![CDATA[TestName = testCases.Framework_001]]>
    </line>
    <line>
      <![CDATA[Test Method resides in testCases.Framework_001]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[About to begin executing Framework_001.afterMethod]]>
    </line>
    <line>
      <![CDATA[Completed executing Framework_001.afterMethod]]>
    </line>
    <line>
      <![CDATA[About to begin executing Framework_002.beforeMethod]]>
    </line>
    <line>
      <![CDATA[Completed executing Framework_002.beforeMethod]]>
    </line>
    <line>
      <![CDATA[About to begin executing Framework_002.VerificationBeforeCall]]>
    </line>
    <line>
      <![CDATA[Completed executing Framework_002.VerificationBeforeCall]]>
    </line>
    <line>
      <![CDATA[TestName = testCases.Framework_002]]>
    </line>
    <line>
      <![CDATA[Test Method resides in testCases.Framework_002]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[About to begin executing Framework_002.afterMethod]]>
    </line>
    <line>
      <![CDATA[Completed executing Framework_002.afterMethod]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="446564" started-at="2017-03-28T09:21:31Z" finished-at="2017-03-28T09:28:57Z">
    <groups>
    </groups>
    <test name="Random Sanity Test Demo" duration-ms="446564" started-at="2017-03-28T09:21:31Z" finished-at="2017-03-28T09:28:57Z">
      <class name="testCases.Framework_002">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testCases.Framework_002@29774679]" name="beforeMethod" is-config="true" duration-ms="48996" started-at="2017-03-28T14:55:40Z" finished-at="2017-03-28T14:56:29Z">
          <reporter-output>
            <line>
              <![CDATA[Completed executing Framework_002.beforeMethod]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="VerificationBeforeCall()[pri:0, instance:testCases.Framework_002@29774679]" name="VerificationBeforeCall" duration-ms="147891" started-at="2017-03-28T14:56:29Z" finished-at="2017-03-28T14:58:57Z">
          <exception class="java.lang.Exception">
            <full-stacktrace>
              <![CDATA[java.lang.Exception
	at utility.Utils.takeScreenshot(Utils.java:99)
	at testCases.Framework_002.VerificationBeforeCall(Framework_002.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
            <line>
              <![CDATA[Completed executing Framework_002.VerificationBeforeCall]]>
            </line>
            <line>
              <![CDATA[TestName = testCases.Framework_002]]>
            </line>
            <line>
              <![CDATA[Test Method resides in testCases.Framework_002]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
            <line>
              <![CDATA[About to begin executing Framework_002.afterMethod]]>
            </line>
          </reporter-output>
        </test-method> <!-- VerificationBeforeCall -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testCases.Framework_002@29774679]" name="afterMethod" is-config="true" duration-ms="227" started-at="2017-03-28T14:58:57Z" finished-at="2017-03-28T14:58:57Z">
          <reporter-output>
            <line>
              <![CDATA[Completed executing Framework_002.afterMethod]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- testCases.Framework_002 -->
      <class name="testCases.Framework_001">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testCases.Framework_001@61832929]" name="beforeMethod" is-config="true" duration-ms="67630" started-at="2017-03-28T14:51:31Z" finished-at="2017-03-28T14:52:38Z">
          <reporter-output>
            <line>
              <![CDATA[Completed executing Framework_001.beforeMethod]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="VerificationDuringCall()[pri:0, instance:testCases.Framework_001@61832929]" name="VerificationDuringCall" duration-ms="181487" started-at="2017-03-28T14:52:38Z" finished-at="2017-03-28T14:55:40Z">
          <exception class="java.lang.Exception">
            <full-stacktrace>
              <![CDATA[java.lang.Exception
	at utility.Utils.takeScreenshot(Utils.java:99)
	at testCases.Framework_001.VerificationDuringCall(Framework_001.java:165)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
            <line>
              <![CDATA[Completed executing Framework_001.VerificationDuringCall]]>
            </line>
            <line>
              <![CDATA[TestName = testCases.Framework_001]]>
            </line>
            <line>
              <![CDATA[Test Method resides in testCases.Framework_001]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
            <line>
              <![CDATA[About to begin executing Framework_001.afterMethod]]>
            </line>
          </reporter-output>
        </test-method> <!-- VerificationDuringCall -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testCases.Framework_001@61832929]" name="afterMethod" is-config="true" duration-ms="278" started-at="2017-03-28T14:55:40Z" finished-at="2017-03-28T14:55:40Z">
          <reporter-output>
            <line>
              <![CDATA[Completed executing Framework_001.afterMethod]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- testCases.Framework_001 -->
    </test> <!-- Random Sanity Test Demo -->
  </suite> <!-- Suite -->
</testng-results>
